import { supabase } from '@/lib/supabase';

export type AuditActionType =
  | 'batch_created'
  | 'batch_submitted'
  | 'batch_approved'
  | 'batch_rejected'
  | 'batch_funded'
  | 'batch_processed'
  | 'contractor_added'
  | 'contractor_edited'
  | 'contractor_deactivated'
  | 'fuel_request_submitted'
  | 'fuel_request_approved'
  | 'fuel_request_rejected'
  | 'trip_log_submitted'
  | 'expense_submitted'
  | 'expense_approved'
  | 'expense_rejected'
  | 'employee_added'
  | 'employee_edited'
  | 'employee_deactivated'
  | 'subscription_added'
  | 'subscription_edited'
  | 'subscription_cancelled'
  | 'subscription_renewed'
  | 'budget_created'
  | 'budget_submitted'
  | 'budget_approved'
  | 'budget_rejected'
  | 'budget_edited'
  | 'document_uploaded'
  | 'document_deleted'
  | 'document_edited'
  | 'bulk_approved'
  | 'profile_updated'
  | 'profile_password_changed'
  | 'profile_viewed_as'
  | 'batch_scheduled'
  | 'director_disbursement_sent'
  | 'director_disbursement_list_viewed'
  | 'director_disbursement_viewed'
  | 'personal_transfer_sent'
  | 'personal_transfer_list_viewed'
  | 'personal_transfer_viewed'
  | 'batch_item_retried'
  | 'batch_receipt_downloaded'
  | 'budget_locked'
  | 'budget_unlocked'
  | 'leave_requested'
  | 'leave_approved'
  | 'leave_rejected'
  | 'leave_cancelled'
  | 'task_created'
  | 'task_updated'
  | 'task_completed'
  | 'task_commented'
  | 'project_created'
  | 'project_updated'
  | 'project_deleted'
  | 'space_created'
  | 'space_updated'
  | 'space_deleted'
  | 'compliance_filed'
  | 'compliance_marked_overdue'
  | 'payroll_created'
  | 'payroll_submitted'
  | 'payroll_approved'
  | 'payroll_paid'
  | 'announcement_posted'
  | 'announcement_removed'
  | 'approval_comment'
  | 'invite_sent'
  | 'invite_revoked'
  | 'company_settings_updated'
  | 'role_changed'
  | 'knowledge_article_created'
  | 'knowledge_article_updated'
  | 'knowledge_article_deleted'
  | 'virtual_card_created'
  | 'virtual_card_updated'
  | 'virtual_card_deactivated'
  | 'goal_created'
  | 'goal_updated'
  | 'goal_completed'
  | 'employee_invite_resent'
  | 'notification_prefs_updated'
  | 'audit_log_exported'
  | 'paystack_recipient_created'
  | 'paystack_transfer_initiated'
  | 'paystack_transfer_succeeded'
  | 'paystack_transfer_failed'
  | 'paystack_transfer_retried'
  | 'payslip_generated'
  | 'payslip_downloaded'
  | 'bank_statement_uploaded'
  | 'bank_reconciliation_matched'
  | 'resubmission_created'
  | 'company_settings_saved'
  | 'report_exported'
  | 'deduction_created'
  | 'deduction_applied'
  | 'user_logged_in'
  | 'user_logged_out'
  | 'paystack_reconciliation_run'
  | 'expense_first_approval'
  | 'expense_deleted'
  | 'budget_deleted'
  | 'leave_deleted'
  | 'fuel_request_deleted'
  | 'client_created'
  | 'client_updated'
  | 'client_deleted'
  | 'data_retention_action'
  | 'platform_export'
  // Reconciled against every logAudit() call site in src/ (TS2345 drift
  // audit) — these were already being passed as action types but were
  // missing from this union, silently forcing callers into `as any`/type
  // errors instead of real compile-time checking.
  | 'anomaly_open'
  | 'anomaly_dismissed'
  | 'anomaly_acknowledged'
  | 'anomaly_escalated'
  | 'anomaly_reviewed'
  | 'anomaly_review_reverted'
  | 'anomaly_record_deleted'
  | 'batch_edited'
  | 'batch_first_approved'
  | 'batch_second_approved'
  | 'batch_item_cancelled'
  | 'batch_item_resolved'
  | 'batch_item_unresolved'
  | 'batch_reconciled'
  | 'batch_cancelled_bulk'
  | 'batch_renamed'
  | 'bulk_paid'
  | 'chatbot_config_updated'
  | 'chatbot_kb_created'
  | 'chatbot_kb_updated'
  | 'chatbot_kb_deleted'
  | 'compliance_deleted'
  | 'compliance_pack_downloaded'
  | 'p9_cards_downloaded'
  | 'contact_updated'
  | 'contact_deleted'
  | 'contractor_deleted'
  | 'employee_deleted'
  | 'permissions_updated'
  | 'salary_increment'
  | 'earning_created'
  | 'ewa_requested'
  | 'ewa_approved'
  | 'ewa_rejected'
  | 'expense_payment_batched'
  | 'fleet_vehicle_added'
  | 'fleet_vehicle_updated'
  | 'fleet_vehicle_deactivated'
  | 'fleet_vehicle_deleted'
  | 'vehicle_inspection_completed'
  | 'repair_request_submitted'
  | 'repair_receipt_uploaded'
  | 'trip_started'
  | 'trip_ended'
  | 'trip_cancelled'
  | 'trip_log_deleted'
  | 'trip_fuel_adjusted'
  | 'fuel_budget_exception_requested'
  | 'fuel_budget_exception_approved'
  | 'fuel_payment_sent'
  | 'fuel_receipt_uploaded'
  | 'fuel_receipt_resubmission_requested'
  | 'fuel_request_completed'
  | 'flutterwave_transfer_initiated'
  | 'flutterwave_transfer_retried'
  | 'flutterwave_transfer_recovered'
  | 'flutterwave_transfer_failed'
  | 'paystack_transfer_recovered'
  | 'invoice_created'
  | 'invoice_updated'
  | 'invoice_deleted'
  | 'leave_reverted'
  | 'payroll_run_recalled'
  | 'payroll_run_deleted'
  | 'salary_disbursed'
  | 'quick_pay_routed_for_approval'
  | 'task_attachment_uploaded'
  | 'task_attachment_deleted'
  | 'whatsapp_group_created'
  | 'whatsapp_group_updated'
  | 'principal_wallet_desync'
  | 'remittance_auto_generated'
  | 'remittance_marked_remitted'
  | 'remittance_confirmed'
  | 'remittance_csv_exported'
  | 'attendance_recorded'
  | 'attendance_updated'
  | 'attendance_deleted';

export interface AuditActor {
  id?: string | null;
  full_name?: string | null;
  email?: string | null;
}

/**
 * Write a row to the audit_logs table via the `log_audit` SECURITY DEFINER RPC.
 *
 * The RPC enforces `performed_by = auth.uid()` server-side — any client-supplied
 * actor is ignored. This closes H-4 (audit_logs INSERT spoofing). The legacy
 * `actor` parameter is retained for source-compat with existing call sites but
 * is no longer trusted by the database.
 */
export async function logAudit(
  actionType: AuditActionType,
  description: string,
  actor?: AuditActor | null,
  metadata?: Record<string, unknown>
): Promise<void> {
  void actor;
  try {
    const { error } = await supabase.rpc('log_audit', {
      p_action_type: actionType,
      p_description: description,
      p_metadata: metadata ?? {},
    });
    if (error) {
      console.warn('[KDOps] log_audit RPC failed:', error.message);
    }
  } catch (err) {
    console.warn('[KDOps] audit log exception:', err);
  }
}
