import { supabase } from '@/lib/supabase';
import type { FlexNumberFormat } from '@/lib/flexFormula';

export type FlexFieldType =
  | 'text' | 'long_text' | 'number' | 'date' | 'checkbox'
  | 'select' | 'multi_select' | 'person' | 'multi_person' | 'task_link'
  | 'url' | 'email' | 'phone' | 'formula';

export const FLEX_FIELD_TYPES: { value: FlexFieldType; label: string }[] = [
  { value: 'text', label: 'Single line text' },
  { value: 'long_text', label: 'Long text' },
  { value: 'number', label: 'Number' },
  { value: 'date', label: 'Date' },
  { value: 'checkbox', label: 'Checkbox' },
  { value: 'select', label: 'Single select' },
  { value: 'multi_select', label: 'Multiple select' },
  { value: 'person', label: 'Person' },
  { value: 'multi_person', label: 'Multiple people' },
  { value: 'task_link', label: 'Linked tasks' },
  { value: 'url', label: 'URL' },
  { value: 'email', label: 'Email' },
  { value: 'phone', label: 'Phone' },
  { value: 'formula', label: 'Formula' },
];

export interface FlexChoice { id: string; label: string; color: string; }
export interface FlexFieldOptions {
  choices?: FlexChoice[];
  /** Column-level hide in the grid — independent of any form's own field visibility. */
  hidden?: boolean;
  /** formula fields only — Airtable-pattern expression, e.g. ROUND({Hours}*{Rate}, 2) */
  formula?: string;
  /** formula fields only — how to display a numeric result. */
  format?: FlexNumberFormat;
}

export interface FlexTable {
  id: string;
  name: string;
  description: string | null;
  icon: string;
  color: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface FlexField {
  id: string;
  table_id: string;
  name: string;
  type: FlexFieldType;
  options: FlexFieldOptions;
  sort_order: number;
  created_at: string;
}

export interface FlexRecord {
  id: string;
  table_id: string;
  data: Record<string, unknown>;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface FlexFormFieldCondition { field_id: string; value: string; }
export interface FlexFormField {
  field_id: string;
  required: boolean;
  /** "Hide this field in this form" — independent of the grid's own hidden flag. */
  condition: FlexFormFieldCondition | null;
  /** For task_link fields: restrict the picker to tasks assigned to whichever
   *  person is selected in this person-type field, excluding completed tasks. */
  filterByPersonField?: string | null;
}

export interface FlexForm {
  id: string;
  table_id: string;
  name: string;
  description: string | null;
  share_token: string;
  is_enabled: boolean;
  fields: FlexFormField[];
  created_by: string | null;
  created_at: string;
}

export function conditionMatches(condition: FlexFormFieldCondition | null, values: Record<string, unknown>): boolean {
  if (!condition) return true;
  const current = values[condition.field_id];
  if (Array.isArray(current)) return current.map(String).includes(condition.value);
  return current !== undefined && current !== null && String(current) === condition.value;
}

// The flex_* tables are brand new and not yet present in the generated
// Database type (regenerated by CI after this migration deploys to
// production). Isolate the escape hatch here so every caller elsewhere
// in the feature stays fully typed against the interfaces above.
const db = supabase as unknown as {
  from: (table: string) => any;
  rpc: (fn: string, args?: Record<string, unknown>) => any;
};

export const flexApi = {
  listTables: () => db.from('flex_tables').select('*').order('created_at', { ascending: false }),
  createTable: (payload: { name: string; description?: string | null; icon?: string; color?: string; created_by?: string | null }) =>
    db.from('flex_tables').insert(payload).select().single(),
  updateTable: (id: string, payload: Partial<FlexTable>) => db.from('flex_tables').update(payload).eq('id', id),
  deleteTable: (id: string) => db.from('flex_tables').delete().eq('id', id),

  listFields: (tableId: string) => db.from('flex_fields').select('*').eq('table_id', tableId).order('sort_order', { ascending: true }),
  createField: (payload: { table_id: string; name: string; type: FlexFieldType; options?: FlexFieldOptions; sort_order?: number }) =>
    db.from('flex_fields').insert(payload).select().single(),
  updateField: (id: string, payload: Partial<Pick<FlexField, 'name' | 'type' | 'options' | 'sort_order'>>) =>
    db.from('flex_fields').update(payload).eq('id', id),
  deleteField: (id: string) => db.from('flex_fields').delete().eq('id', id),

  listRecords: (tableId: string) => db.from('flex_records').select('*').eq('table_id', tableId).order('created_at', { ascending: true }),
  createRecord: (tableId: string, data: Record<string, unknown>, createdBy: string | null) =>
    db.from('flex_records').insert({ table_id: tableId, data, created_by: createdBy }).select().single(),
  updateRecord: (id: string, data: Record<string, unknown>) =>
    db.from('flex_records').update({ data, updated_at: new Date().toISOString() }).eq('id', id),
  deleteRecord: (id: string) => db.from('flex_records').delete().eq('id', id),

  listForms: (tableId: string) => db.from('flex_forms').select('*').eq('table_id', tableId).order('created_at', { ascending: false }),
  createForm: (payload: { table_id: string; name: string; description?: string | null; fields?: FlexFormField[]; created_by?: string | null }) =>
    db.from('flex_forms').insert(payload).select().single(),
  updateForm: (id: string, payload: Partial<Pick<FlexForm, 'name' | 'description' | 'is_enabled' | 'fields'>>) =>
    db.from('flex_forms').update(payload).eq('id', id),
  deleteForm: (id: string) => db.from('flex_forms').delete().eq('id', id),

  getPublicForm: (shareToken: string) => db.rpc('get_flex_form', { p_share_token: shareToken }),
  submitPublicForm: (shareToken: string, data: Record<string, unknown>) =>
    db.rpc('submit_flex_form', { p_share_token: shareToken, p_data: data }),
  getFormTasks: (shareToken: string, personId: string) =>
    db.rpc('get_flex_form_tasks', { p_share_token: shareToken, p_assignee_id: personId }),
};
