import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { RefTable, RefSection } from '@/components/guide/shared';
import { History, Wallet, Sparkles } from 'lucide-react';

export function TechOverviewSection() {
  return (
    <>
      <h2 className="text-xl font-semibold mb-1">Change History & Overview</h2>
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2">
            <History className="h-4 w-4 text-primary" /> Platform change history
          </CardTitle>
        </CardHeader>
        <CardContent className="text-xs space-y-2 leading-relaxed">
          <p><strong>Phase 1 — Tighter access control.</strong> Only the right people can see audit logs, tasks, comments, referrals, and deductions. Webhook duplicates from Paystack no longer create duplicate transactions. Two missing tables (salary increments, revenue entries) were added.</p>
          <p><strong>Phase 2 — More resilient pages.</strong> A bug on one page no longer brings down the whole app — the user sees a friendly error message instead. The Payments page is much faster (was making many small database calls in a loop). Background refreshing slows down when a tab is inactive. Long employee profiles now use page navigation.</p>
          <p><strong>Phase 3 — Sanity checks &amp; receipts.</strong> The database now rejects unrealistically large amounts (e.g. ₦50 billion typed by accident). Risky file types (.exe, .html, .js) are blocked from upload. A "Reconcile" button on Payments re-checks stuck transfers. Every login and logout is recorded in the audit log.</p>
          <p><strong>Phase 4 — Login &amp; browser security.</strong> 5 wrong passwords in 15 minutes briefly locks the account. Failed attempts are saved for admins to review. The browser is told which servers it can talk to so injected scripts can't reach unknown sites. App-wide error reporting is wired up (Sentry-ready).</p>
          <p><strong>Phase 5–14 — Feature build-out.</strong> Two-approver workflow for big expenses, budget locking, leave balance tracking, payroll advances, virtual cards, knowledge base, goals, announcements, compliance calendar, and contractor profiles.</p>
          <p><strong>Phase 15 — Always fresh data.</strong> When you switch back to a browser tab, lists automatically pull the latest numbers so you never see stale data.</p>
          <p><strong>P0 Go-live hardening.</strong> Admins can first-approve their own expenses (others can't). The Approvals page caps how many rows it loads at once. Our server APIs reject calls from unknown websites. Database queries are faster thanks to indexes. Passwords must be 12+ characters with letters and numbers. Logging out cleans up live data subscriptions. All file uploads are limited to 10 MB.</p>
          <p><strong>P1 — Payments page crash fixed.</strong> The page used to crash with "Cannot access before initialization" because some code ran in the wrong order. The fix is now enforced automatically by the linter, so it cannot come back.</p>
          <p><strong>P1 — Safer delete.</strong> Deleting an expense, document, budget, leave request, or fuel request no longer wipes it permanently. The row is hidden from every screen but stays in the database, so an admin can recover it from the Supabase dashboard if it was a mistake.</p>
          <p><strong>P1 — Query caps everywhere.</strong> Every list in the app now has a maximum number of rows it fetches at once. This stops pages from getting slower as your data grows. Covers Dashboard, Budgets, Leave, Approvals, Fleet, Reports, plus supporting lists (departments, budget line items, knowledge versions, employee directories, tags).</p>
          <p><strong>P1 — Auto-trim.</strong> Spaces accidentally typed before or after a value (company name, RC number, TIN, address, website, payment batch name) are stripped automatically before saving.</p>
          <p><strong>P1 — No more double-clicks.</strong> Buttons like Submit, Approve, Lock, Delete on Budgets — and Add note, Affiliate toggle, Deactivate elsewhere — grey out the moment you click them. The screen updates immediately; if the server rejects the change, the screen reverts and shows an error.</p>
          <p><strong>P1 — Branded confirmation pop-ups.</strong> When you delete a subscription, revert a leave approval, or delete an employee document, you see the app's own confirmation box instead of the plain browser pop-up. Same look and feel everywhere.</p>
          <p><strong>P1 — Screen-reader friendliness &amp; cleaner CSV.</strong> Buttons that show only an icon (Pause, Edit, Delete, History) now announce what they do to assistive technology. CSV exports of Contacts, Goals, and Referrals show dates as 27/04/2026 instead of raw timestamps like 2026-04-27T14:00:00Z.</p>
          <p><strong>P1 — Clients module.</strong> New CRM page to track clients (active, inactive, prospect) with contract values, contact details, industry, start date, and notes. Includes search, status filter, pagination, CSV export, and soft delete. Accessible under CRM → Clients in the sidebar.</p>
          <p><strong>P1 — Paystack fee fix.</strong> The Paystack Fees figure on Reports was always ₦0 because the per-transfer fee column is only populated after a real Paystack webhook fires. The calculation now falls back to an estimate (1.5% of transfer amount, minimum ₦50, maximum ₦2,000) for transfers where the actual fee has not yet been recorded, so the Reports P&amp;L shows a realistic figure even during testing.</p>
          <p><strong>P1 — Mobile dialogs &amp; date sanity.</strong> Forms on Compliance and Budgets no longer overflow on small screens — they now scroll inside the dialog instead of running off the page. Date inputs (Client start date, Expense date, Budget periods) now reject unrealistic years like 1900 or 9999, and the budget end date can never be set before the start date.</p>
          <p><strong>P1 — Faster client entry.</strong> The "Add Client" form now puts the cursor in the Name field automatically, so you can start typing immediately without clicking. The Compliance page also shows a friendly "No filings yet" message with guidance for new admins instead of an empty table.</p>
          <p><strong>P1 — Dashboard discovery.</strong> The new Clients module now appears in the Dashboard's Quick Actions panel so it's reachable in one click from anywhere in the app.</p>
          <p><strong>P1 — Client profile pages.</strong> Clicking on any client in the Clients list now opens a dedicated profile page for that client. From there you can edit all details, track contract value, change their status (active / inactive / prospect), and add timestamped notes — the same way you can add notes on a Contact profile. The remove button on the profile also works like the list view: the client is hidden but kept in the database.</p>
          <p><strong>P1 — Compliance keyboard shortcut.</strong> In the "New statutory filing" form, pressing Enter now saves the filing — just like clicking the "Save filing" button. This saves time when quickly logging multiple filings in a row.</p>
          <p><strong>P1 — Reports stopped guessing Paystack fees.</strong> The P&amp;L and Payments reports used to show an estimated Paystack fee figure (1.5% of the transfer amount) which was almost never accurate. The "Paystack Fees" stat card and chart bar have been removed from both the P&amp;L and Payments tabs in Reports. The actual fees Paystack charges (e.g. ₦10 per transfer, plus stamp duty) appear as real entries on the Transactions page, where they naturally count toward what you spent.</p>
          <p><strong>P1 — Friendlier Clients error.</strong> If the Clients table has not been created in the database yet, the page used to show a confusing "schema cache" error from Supabase. It now shows a clear message explaining that the database migration needs to be deployed by running "supabase db push" — so admins know exactly what to do.</p>
          <p><strong>P1 — Paystack fees as separate rows in Transactions.</strong> The Transactions page now shows Paystack transfer fees as their own rows — exactly like the Paystack ledger does. Each completed transfer that has a recorded fee produces a "Charge for transfer: TRF_xxx" row (in amber) directly below the transfer itself. Clicking a fee row navigates to the same batch detail page as the transfer. A "Fees" tab lets you filter to fee rows only.</p>
          <p><strong>P1 — Paystack fees count toward P&amp;L and Payment costs.</strong> Reports now includes real Paystack transfer fees (from webhook data, never estimated) in operating costs. The P&amp;L tab shows a "Paystack Fees" stat card and stacks fees in the monthly chart. Net Profit is now Revenue − disbursements − expenses − actual Paystack fees. The Payments tab also shows a Paystack Fees total, and the CSV export includes the fee column per batch.</p>
          <p><strong>Phase 2 — Invoices module.</strong> A full Invoices page (Finance → Invoices in the sidebar) lets you create, send, and track client invoices. Each invoice supports dynamic line items, Nigerian VAT at 7.5% (configurable to 0 / 5 / 7.5 / 10%), and a clear status workflow: draft → sent → paid | overdue | cancelled. Overdue is detected automatically — no scheduled job needed. Invoices are linked to the Clients CRM. Print-ready view and CSV export included.</p>
          <p><strong>Phase 2 — Dashboard expiry alerts.</strong> The Dashboard now shows an amber alert panel for anything that needs attention in the next 30 days: documents whose expiry date is approaching and compliance filings whose due date is close. Clicking an alert takes you directly to the Documents or Compliance page. Only visible to Finance / Admin / Super Admin roles (not personal dashboards).</p>
          <p><strong>Phase 3 — Vendor Registry.</strong> A dedicated Vendors page (Operations group in the sidebar) stores all suppliers — utilities, SaaS, service providers, logistics partners. Each vendor record holds contact info, CAC RC number, TIN, bank details, payment terms, and contract start/end dates. Contracts expiring within 30 days surface as amber badges. Soft delete and CSV export included. Accessible to Finance, Operations, Admin, and Super Admin.</p>
          <p><strong>Phase 3 — Petty Cash Management.</strong> The Petty Cash page (Finance group) lets you create one or more cash funds (e.g. "Head Office Float", "Lagos Branch"). Each fund has a custodian, an opening balance, and a running current balance that is automatically recalculated by a database trigger after every entry. Disbursements and replenishments are recorded individually with date, purpose, payee, and category. Low-balance alerts appear when a fund drops below ₦5,000.</p>
          <p><strong>Phase 3 — Performance Reviews.</strong> The Performance page (Operations group) introduces structured review cycles — annual, mid-year, quarterly, or probation. Each cycle contains individual reviews (manager, self-assessment, or peer). Reviewers rate employees on five competencies (Delivery, Communication, Teamwork, Initiative, Leadership) on a 1–5 scale; the overall rating is computed as the average. Status flow: draft → submitted → acknowledged. A progress bar on each cycle shows how many reviews have been submitted. Overdue cycles are flagged in red.</p>
          <p><strong>Phase 3 — Petty Cash removed.</strong> The Petty Cash module was built but removed at the user's request — all expenses go through bank transfers and the Expenses module, making a separate cash float tracker redundant. The underlying database tables (petty_cash_funds, petty_cash_entries) remain in the schema but the UI is gone.</p>
          <p><strong>Phase 4 — Asset Register.</strong> A fixed assets page (Finance → Assets) tracks every company asset — IT equipment, motor vehicles, furniture, plant &amp; machinery, buildings, and leasehold improvements. Book value is calculated live using straight-line or reducing-balance depreciation. CITA capital allowance rates (initial and annual) are pre-filled by asset category per Nigerian Companies Income Tax Act rules. Insurance expiry dates trigger 30-day amber badges. Assets can be assigned to employees and departments. Disposed and written-off assets are tracked separately from active ones. CSV export included.</p>
          <p><strong>Phase 4 — Employee Loans removed.</strong> A standalone Loans module was built but removed — the existing employee_advances system in Payroll already handles staff advances with monthly deductions, auto-settlement, and payroll integration. The loan migration (employee_loans table) remains in the schema but the UI is gone.</p>
          <p><strong>Phase 4 — Training &amp; Certifications.</strong> The Training page (Operations → Training) records every employee course and certification. Certifications with expiry dates automatically show as "Expired" when past due — no job needed. Expiry dates within 30 days surface as amber badges. Mandatory training (safety, compliance) is flagged separately from optional development. Filters by employee, type, category, and status. CSV export included. Training costs are tracked for budget analysis.</p>
          <p><strong>Phase 5 — Project Tracker.</strong> A Projects page (Workspace group) links projects to clients (CRM), owners, and departments. Status workflow: planning → active → on_hold → completed / cancelled. Priority levels: critical, high, normal, low. Budget in ₦. Inline milestones with drag-sortable order — mark each milestone complete with a single click. Linked tasks from the Tasks module are counted and displayed per project. Overdue detection on active projects whose end date has passed. CSV export included.</p>
          <p><strong>Phase 5 — Employee Benefits.</strong> A Benefits page (Operations group) tracks all statutory and voluntary benefits per employee: HMO (NHIS), Pension (PFA with RSA PIN), Group Life, and other benefits. Premium amounts and frequency (monthly / quarterly / annually) are stored; monthly equivalent is computed on the fly. Expiry dates within 30 days surface as amber badges. Summary cards show active enrolment counts by type. CSV export included.</p>
          <p><strong>Phase 5 — Onboarding &amp; Offboarding.</strong> An Onboarding page (Operations group) manages joining and exit checklists for employees. Creating a checklist pre-populates it with 11 default onboarding items (documentation, IT setup, HR admin, finance, training, equipment, introduction) or 8 offboarding items — or you can start blank. Each item can be assigned to a team member with a due date. Tick items complete individually; a progress bar shows overall completion. Status is derived in-app (pending / in-progress / completed) — no DB trigger needed. CSV export included.</p>
          <p><strong>Phase 6 — Recruitment Pipeline.</strong> A Recruitment page (Operations group) manages the full hiring lifecycle: create job openings with title, department, employment type (full-time / part-time / contract / intern), salary range, and closing date. Add applicants to each opening; move them through the pipeline stages: New → Screening → Interview 1 → Interview 2 → Offer → Hired / Rejected. Record interview dates, assigned interviewers, offer amounts, and rejection reasons. Stage-filter buttons on each opening show counts per stage. Summary cards track active openings, total applicants, offers out, and hired count. CSV export included.</p>
          <p><strong>Phase 6 — Attendance &amp; Timesheets.</strong> An Attendance page (Operations group) records daily attendance per employee. Each record captures clock-in and clock-out times (stored as TIME — single-timezone Nigeria WAT), attendance status (present / absent / late / half-day / remote / on-leave / public holiday), and overtime minutes. One record per employee per date is enforced by a UNIQUE constraint — upsert on conflict handles re-submission. The page shows a month navigator with a running summary of present, late, absent, and on-leave counts. Overtime hours are totalled for the period. CSV export per month included.</p>
          <p><strong>Phase 6 — Disciplinary Records.</strong> A Disciplinary page (Admin + Super Admin only) manages formal HR actions per Nigerian Labour Act requirements. Incident types cover the full ladder: verbal warning → written warning → final warning → query / show-cause → suspension → termination, plus counselling and other. Each record stores the subject, incident details, formal outcome, and the number of suspension days (if applicable). Employees can formally respond to queries (show-cause letters) via the built-in response thread. Records can be acknowledged (confirming the employee received the notice — required for fair hearing) and expunged with a reason after a clean-record period. Expunged records remain in the audit trail but are hidden from active history unless "Show expunged" is toggled. CSV export included.</p>
          <p><strong>Phase 7 — Fleet Intelligence.</strong> The Fleet Dashboard tab now opens with a Fleet Insights Panel — a composite health score (0–100%) for each vehicle based on fuel efficiency (20%), maintenance compliance (30%), document/compliance status (30%), and inspection results (20%). Smart insights engine generates actionable alerts: overdue maintenance, budget overruns, anomaly rates above 15%, unresolved inspection defects, low fuel efficiency, and week-over-week spend trends. Quick action buttons jump to inspections, maintenance, anomalies, or compliance. Below the insights panel, a Fuel Cost Optimizer ranks vehicles by cost-per-km over 30 days, highlights the best fuel station by average price per litre, and calculates monthly savings opportunity by bringing worst performers to fleet average.</p>
          <p><strong>Phase 7 — Inspection Defect Resolution.</strong> Inspection defects now have a structured resolution workflow. Each defect card shows a green "Resolve" button that opens a dialog with 8 action options: repaired, replaced, adjusted, cleaned, calibrated, temporary_fix, deferred, or not_required. Resolution includes optional repair cost (₦) and notes. Resolved defects show a green "Resolved" badge with the action taken. Available to all authenticated users, not just admins.</p>
          <p><strong>Phase 7 — Document Management Overhaul.</strong> The Documents page was completely rebuilt. New features: (1) Folder system — create folders with custom colors, navigate with breadcrumbs, nest documents inside folders. (2) Entity linking — tag any document to a client, employee, vehicle, or project for cross-referencing. (3) Drag &amp; drop upload — drop files anywhere on the page. (4) Bulk upload — select multiple files at once with a progress bar. (5) Grid + list view toggle. (6) Dashboard stats cards showing total docs, expiring soon, expired, linked count, and folder count. (7) Entity filter in toolbar — filter by client/employee/vehicle/project/unlinked. (8) Document detail dialog with full metadata. (9) Template flag for reusable documents. (10) Access tracking — records last_accessed_at and access_count on every download. (11) Expanded categories: contract, agreement, receipt, invoice, ID document, policy, report, proposal, letter, certificate, license, insurance, tax, HR, onboarding, template, other. Upload roles expanded to include finance and operations (not just admin).</p>
          <p><strong>Security audit remediation (2026-08-15/16).</strong> A forensic security/ops audit and a separate mobile/design audit both ran against the live system; every Critical and High finding, plus the highest-value Medium findings, were actioned: (1) Closed 53 RLS policies across the database that used <code>USING (true)</code> — including contractors' bank details, which were readable and writable by any authenticated user. (2) Fixed 3 edge function bugs: <code>record-failed-login</code> threw a ReferenceError on every call, <code>data-retention-runner</code> had an auth bypass via a spoofable request-body flag, <code>send-email</code> let any authenticated user send email/SMS as the company (now restricted to super_admin/admin/operations). (3) Restored server-side MFA step-up (password + fresh TOTP code) for payment/expense approvals — a full step-up system existed before but was silently deleted in a later "remove restrictions" migration with no server-side AAL2 check left behind. Rebuilt it as opt-in (<code>company_settings.approval_step_up_required</code>, off by default) since 0 of 10 current approvers had TOTP enrolled at the time — a super_admin turns it on from Settings → Security once approvers are enrolled, and a live "X of Y enrolled" counter prevents flipping it on blind. (4) Closed a latent gap where the <code>employee_earnings</code> table's broad-access policy fix only worked because the original broad policy never actually ran in production — a fresh database rebuild would have silently reopened it; now explicitly dropped by name. (5) Mobile/UI audit Tier 1: 44px minimum touch targets app-wide (was as low as 32px on approve/reject buttons), lazy-loaded the receipt PDF libraries (removed 181 kB from every batch page load), replaced all 23 native browser confirm() popups with a proper in-app dialog — including the two irreversible payroll actions (recall a run to draft, delete a draft) that were previously bare OS alerts, added mobile card views to the money-critical tables that had none, added proper form labels to the highest-traffic forms (bank/salary fields previously had zero screen-reader association), and migrated the highest-traffic dialogs to a bottom-sheet layout on mobile.</p>
          <p><strong>Pre-launch hardening (2026-04-29).</strong> Six go-live blockers and four high-priority issues resolved before production launch: (1) Batch payments now run server-side (edge function, 50-item chunks, 8-way concurrency, 120 s budget) — a 1,000-transfer batch completes in ~3.5 min regardless of tab state. A pg_cron watchdog fires every minute to rescue orphaned batches. (2) Optimistic concurrency guard prevents double-payment when two admins click Process simultaneously. (3) Paystack fees now display on batch items and fuel requests with a three-tier fallback (webhook data → raw JSON → tier estimate). (4) Fleet Activity tab restricted to admin/finance/super_admin; PermissionsEditor updated with fleet.view_activity key. (5) Security hardening: BEFORE UPDATE trigger blocks role self-elevation, transactions_view switched to security_invoker, company_settings locked to admin/finance/super_admin, fuel request RLS widened to include finance role. (6) Hot-table indexes added on audit_logs, notifications, and batch_items. Status preconditions added to all state transitions (batch and fuel) to prevent stale-state races. CI workflow added (lint + typecheck + build on every push to main).</p>
          <p className="text-muted-foreground border-t pt-2 mt-2">
            Database changes live in <code>supabase/migrations/</code> · Server-side helpers in <code>supabase/functions/</code> · After deploying, run <code>supabase db push</code> to apply any new database changes.
          </p>
        </CardContent>
      </Card>

      <RefSection icon={Wallet} title="Money caps (all modules)">
        <RefTable
          cols={['What', 'Maximum', 'Why']}
          rows={[
            { a: 'Single payment batch (total)',      b: '₦5,000,000,000', c: 'Catches typo on bulk runs' },
            { a: 'Single transfer (one beneficiary)', b: '₦100,000,000',   c: 'Single Paystack transfer guard' },
            { a: 'One expense submission',            b: '₦100,000,000',   c: 'Catches accidental extra digit' },
            { a: 'One fuel request',                  b: '₦5,000,000',     c: 'Highest plausible single fuel-up' },
            { a: 'One subscription',                  b: '₦50,000,000',    c: 'SaaS / utility max' },
            { a: 'One revenue entry',                 b: '₦5,000,000,000', c: 'Monthly revenue ceiling' },
            { a: 'Annual budget (per category)',      b: '₦5,000,000,000', c: 'Yearly planning ceiling' },
            { a: 'Salary advance',                    b: '₦50,000,000',    c: 'Per-employee advance' },
            { a: 'Annual salary',                     b: '₦100,000,000',   c: 'Per-employee yearly comp' },
          ]}
        />
      </RefSection>

      <RefSection icon={Sparkles} title="What we polished recently (in plain English)">
        <RefTable
          cols={['What you will notice', 'How it works']}
          rows={[
            { a: 'Branded "Are you sure?" pop-ups',      b: 'Deleting a subscription, reverting a leave approval, removing an employee document, or running Reconcile on Payments now shows the app\'s own confirmation box instead of the plain browser one.' },
            { a: 'No accidental double-clicks',          b: 'Buttons like Submit, Approve, Lock, Delete (Budgets), Add note (Contacts), Affiliate toggle (Referrals), Deactivate (Contractors) grey out the moment you click them — so the same change cannot be made twice.' },
            { a: 'Instant on-screen feedback',           b: 'Toggling an affiliate, deactivating a contractor, or adding a note updates the screen straight away. If the server rejects the change, the screen reverts and you see an error.' },
            { a: 'Friendlier for screen readers',        b: 'Icon-only buttons (Pause, Edit, Delete, History) now announce what they do to assistive technology — important for low-vision or keyboard-only users.' },
            { a: 'Cleaner dates in CSV exports',         b: 'Contacts, Goals, and Referrals CSV exports show dates like 27/04/2026 instead of raw timestamps like 2026-04-27T14:00:00Z.' },
            { a: 'Stray spaces auto-stripped',           b: 'Spaces accidentally typed before or after company name, RC number, TIN, website, address, or payment batch name are removed automatically before saving.' },
            { a: 'No silent page failures',              b: 'If a page can\'t load its data (e.g. brief network issue), you see a red error toast — never a blank screen with no explanation.' },
            { a: 'Click a client to open its profile',  b: 'Clicking any row in the Clients list opens a full profile page where you can edit details, add notes, and change status — without opening a small dialog.' },
            { a: 'Notes on client profiles',            b: 'You can add timestamped notes to any client the same way you can for Contacts. Each note shows the date and time it was added, and the full history is visible in one place.' },
            { a: 'Enter key saves compliance filings',  b: 'In the "New statutory filing" form, pressing Enter submits the form — useful when adding several filings quickly without reaching for the mouse.' },
            { a: 'No more guessed Paystack fees',        b: 'Reports used to show an estimated 1.5% Paystack fee figure that was almost always wrong. That stat card and chart bar are gone — actual transfer fees (₦10 charges, stamp duty etc.) appear as real entries on the Transactions page and naturally count toward operating costs.' },
            { a: 'Helpful Clients setup message',        b: 'If an admin opens the Clients page before the database migration has been deployed, the page now says "ask an admin to run supabase db push" instead of a confusing "schema cache" error.' },
            { a: 'Paystack fees as their own rows',       b: 'Each completed Paystack transfer now generates a separate "Charge for transfer: TRF_xxx" row (shown in amber) in the Transactions list — the same way the Paystack ledger shows it. Use the Fees filter tab to view only fee rows. The TRF reference matches Paystack\'s own ledger exactly.' },
            { a: 'Paystack fees in P&L and Payments',     b: 'Real transfer fees (from webhook data, never estimated) now count toward operating costs in Reports. P&L shows a dedicated "Paystack Fees" card and stacks fees in the chart. Net Profit = Revenue − disbursements − expenses − fees.' },
            { a: 'Invoices module',                       b: 'Finance can now create and send invoices to clients with line items, VAT (default 7.5% Nigerian standard), and a status workflow (draft → sent → paid / overdue / cancelled). Overdue is auto-detected by comparing due_date to today. Print-ready layout and CSV export included.' },
            { a: '30-day expiry alerts on Dashboard',     b: 'An amber panel on the main Dashboard shows documents expiring soon and compliance filings due within 30 days. Clicking takes you straight to the relevant page. Visible to Finance / Admin / Super Admin only.' },
            { a: 'Vendor Registry',                       b: 'A Vendors page stores all suppliers with contact info, bank details, CAC/TIN, payment terms, and contract dates. Contracts expiring within 30 days are flagged in amber — no more scrambling to find a supplier\'s bank account before a payment.' },
            { a: 'Petty Cash Management',                 b: 'Create cash funds with custodians. Each disbursement or replenishment adjusts the running balance instantly (via a DB trigger). Low-balance warning shows when a fund drops below ₦5,000. Export a fund\'s full history to CSV.' },
            { a: 'Performance Reviews',                   b: 'Run structured review cycles (annual / mid-year / quarterly / probation). Rate employees on five competencies (1–5 stars). Manager, self-assessment, and peer reviews are tracked separately. A progress bar shows how many reviews have been submitted in each cycle.' },
            { a: 'Asset Register',                        b: 'Track fixed assets with live book value (straight-line or reducing-balance depreciation). CITA capital allowance rates are pre-filled by category. Insurance expiry triggers 30-day alerts. Assets can be assigned to employees and departments. Disposal and write-off tracking included.' },
            { a: 'Training & Certifications',             b: 'Record courses and certifications per employee. Certifications auto-show as "Expired" when past their expiry date. 30-day amber badges for upcoming renewals. Mandatory vs optional flag for compliance training. Filters by employee, type, category, and status.' },
            { a: 'Project Tracker',                       b: 'Create and manage projects linked to clients, owners, and departments. Add milestones inline and tick them complete. Linked tasks are counted per project. Overdue projects are automatically flagged. Priority and status filters included.' },
            { a: 'Employee Benefits',                     b: 'Record HMO, Pension (PFA), Group Life, and other benefits per employee. Store policy numbers, RSA PINs, premiums, and expiry dates. Monthly cost equivalent is computed on the fly for quarterly or annual premiums. Expiry alerts at 30 days.' },
            { a: 'Onboarding & Offboarding',              b: 'Generate joining or exit checklists in one click — pre-filled with Nigerian HR best-practice default items. Tick items complete individually and assign them to team members. Progress bar shows overall completion without any database trigger.' },
            { a: 'Recruitment Pipeline',                   b: 'Post job openings with salary range, employment type, and closing date. Move applicants through a 7-stage pipeline (New → Screening → Interviews → Offer → Hired / Rejected). Track interview dates, assigned interviewers, and offer amounts. Stage-filter buttons on each opening show live counts.' },
            { a: 'Attendance & Timesheets',                b: 'Log daily clock-in/out and attendance status per employee. Month navigator with running totals for present, late, absent, and on-leave. Overtime minutes tracked per day and summed for the period. One record per employee per date enforced at the database level.' },
            { a: 'Disciplinary Records',                   b: 'Full disciplinary ladder: verbal → written → final warning → query → suspension → termination. Employee response thread for show-cause replies (required for fair hearing). Acknowledge receipt, expunge after clean-record period. Visible to Admin and Super Admin only.' },
            { a: 'Fleet Insights Panel',                    b: 'The Fleet Dashboard now opens with a health score panel. Each vehicle gets a composite 0–100% health score based on fuel efficiency (20%), maintenance compliance (30%), document/compliance (30%), and inspection results (20%). Smart insights engine generates alerts: overdue maintenance, budget overruns, anomaly rates > 15%, unresolved defects, low fuel efficiency, and week-over-week spend trends. Quick-action buttons jump directly to inspections, maintenance, anomalies, or compliance.' },
            { a: 'Fuel Cost Optimizer',                     b: 'Below the Fleet Insights Panel, a cost optimizer ranks vehicles by cost-per-km over 30 days. Highlights the best fuel station by average price per litre. Calculates monthly savings opportunity by bringing worst performers to fleet average. Vehicles rated as "Efficient" (below average cost/km) or "High" (above average).' },
            { a: 'Inspection Defect Resolution',            b: 'Inspection defects now have a structured resolution workflow. Green "Resolve" button opens a dialog with 8 action options (repaired, replaced, adjusted, cleaned, calibrated, temporary_fix, deferred, not_required). Optional repair cost and notes. Resolved defects show a green badge. Available to all users.' },
            { a: 'Document Management Overhaul',            b: 'Documents page rebuilt with: folder system (custom colours, breadcrumb navigation), entity linking (tag to client/employee/vehicle/project), drag-and-drop upload, bulk upload with progress bar, grid + list view toggle, dashboard stats (total/expiring/expired/linked/folders), entity filter toolbar, document detail dialog, template flag, access tracking (last_accessed_at + access_count), 17 document categories. Upload roles expanded to include finance and operations.' },
          ]}
        />
      </RefSection>
    </>
  );
}
