-- Invoice management — Finance industry best practice for Nigerian SMBs.
--
-- Key design decisions:
--   • line_items stored as JSONB (no separate table) — invoice history is
--     immutable once sent; keeping items inline avoids orphan-row complexity.
--   • vat_rate defaults to 7.5 (Nigerian standard since the 2020 Finance Act).
--   • client_name / client_email are denormalized so invoice history is
--     preserved even if the client record is later deleted.
--   • invoice_number generated by the application as INV-YYYY-NNNN.
--   • Soft delete (deleted_at) consistent with the rest of the platform.
--   • status: draft → sent → paid | overdue | cancelled
--     Overdue is enforced in the application whenever status=sent AND
--     due_date < today — no scheduled DB job needed.

CREATE TABLE IF NOT EXISTS public.invoices (
  id               UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_number   TEXT         NOT NULL,
  client_id        UUID         REFERENCES public.clients(id) ON DELETE SET NULL,
  client_name      TEXT         NOT NULL,
  client_email     TEXT         DEFAULT NULL,
  issue_date       DATE         NOT NULL DEFAULT CURRENT_DATE,
  due_date         DATE         NOT NULL,
  status           TEXT         NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled')),
  line_items       JSONB        NOT NULL DEFAULT '[]',
  -- line_items format: [{id, description, quantity, unit_price_ngn, amount_ngn}]
  subtotal_ngn     NUMERIC      NOT NULL DEFAULT 0 CHECK (subtotal_ngn >= 0),
  vat_rate         NUMERIC      NOT NULL DEFAULT 7.5 CHECK (vat_rate >= 0 AND vat_rate <= 100),
  vat_amount_ngn   NUMERIC      NOT NULL DEFAULT 0,
  total_ngn        NUMERIC      NOT NULL DEFAULT 0,
  notes            TEXT         DEFAULT NULL,
  payment_terms    TEXT         NOT NULL DEFAULT 'Net 30',
  paid_date        DATE         DEFAULT NULL,
  created_by       UUID         REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ  DEFAULT NULL
);

-- Keep updated_at current automatically
CREATE OR REPLACE FUNCTION public.set_invoices_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS invoices_updated_at ON public.invoices;
CREATE TRIGGER invoices_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.set_invoices_updated_at();

-- Performance indexes
CREATE INDEX IF NOT EXISTS invoices_status_idx
  ON public.invoices (status) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS invoices_client_idx
  ON public.invoices (client_id) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS invoices_due_date_idx
  ON public.invoices (due_date) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS invoices_deleted_at_idx
  ON public.invoices (deleted_at);

-- Row Level Security
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read invoices"
  ON public.invoices FOR SELECT
  USING (auth.uid() IS NOT NULL AND deleted_at IS NULL);

CREATE POLICY "Finance can insert invoices"
  ON public.invoices FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Finance can update invoices"
  ON public.invoices FOR UPDATE
  USING (auth.uid() IS NOT NULL);
