-- Fixed Assets Register
--
-- Design decisions:
--   • asset_number generated by the app (AST-YYYY-NNNN).
--   • depreciation_method: straight_line only for now (most common for FIRS capital allowance).
--     book_value is NOT stored — always derived: cost - accumulated depreciation as of today.
--     The application computes this at query time to stay accurate without scheduled jobs.
--   • Nigerian CITA capital allowances differ by category (e.g. plant & machinery 25%,
--     motor vehicles 25%, furniture 20%, buildings 10%). initial_allowance_rate and
--     annual_allowance_rate store the applicable rates so the app can compute allowances.
--   • assigned_to (user) + department_id let you track custody.
--   • insurance_expiry follows the same 30-day alert pattern as documents.
--   • status: active | disposed | written_off
--   • disposal_date + disposal_proceeds_ngn capture the sale/scrap event.
--   • Soft delete consistent with rest of platform.

CREATE TABLE IF NOT EXISTS public.assets (
  id                       UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  asset_number             TEXT         NOT NULL UNIQUE,
  name                     TEXT         NOT NULL,
  category                 TEXT         NOT NULL
                             CHECK (category IN (
                               'plant_machinery','motor_vehicle','furniture_fittings',
                               'it_equipment','land_building','leasehold_improvement','other'
                             )),
  description              TEXT         DEFAULT NULL,
  purchase_date            DATE         NOT NULL,
  cost_ngn                 NUMERIC      NOT NULL CHECK (cost_ngn >= 0),
  useful_life_years        NUMERIC      NOT NULL DEFAULT 5 CHECK (useful_life_years > 0),
  salvage_value_ngn        NUMERIC      NOT NULL DEFAULT 0 CHECK (salvage_value_ngn >= 0),
  depreciation_method      TEXT         NOT NULL DEFAULT 'straight_line'
                             CHECK (depreciation_method IN ('straight_line','reducing_balance')),
  -- CITA capital allowance rates (as percentages, e.g. 25.0 = 25%)
  initial_allowance_rate   NUMERIC      NOT NULL DEFAULT 0,
  annual_allowance_rate    NUMERIC      NOT NULL DEFAULT 0,
  -- Location & custody
  location                 TEXT         DEFAULT NULL,
  assigned_to              UUID         REFERENCES auth.users(id) ON DELETE SET NULL,
  department_id            UUID         REFERENCES public.departments(id) ON DELETE SET NULL,
  -- Insurance
  insurer                  TEXT         DEFAULT NULL,
  insurance_policy_number  TEXT         DEFAULT NULL,
  insurance_expiry         DATE         DEFAULT NULL,
  insurance_value_ngn      NUMERIC      DEFAULT NULL,
  -- Disposal
  status                   TEXT         NOT NULL DEFAULT 'active'
                             CHECK (status IN ('active','disposed','written_off')),
  disposal_date            DATE         DEFAULT NULL,
  disposal_proceeds_ngn    NUMERIC      DEFAULT NULL,
  disposal_notes           TEXT         DEFAULT NULL,
  -- Housekeeping
  notes                    TEXT         DEFAULT NULL,
  created_by               UUID         REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  deleted_at               TIMESTAMPTZ  DEFAULT NULL,
  CONSTRAINT disposal_date_requires_disposed CHECK (
    disposal_date IS NULL OR status IN ('disposed','written_off')
  )
);

CREATE OR REPLACE FUNCTION public.set_assets_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS assets_updated_at ON public.assets;
CREATE TRIGGER assets_updated_at
  BEFORE UPDATE ON public.assets
  FOR EACH ROW EXECUTE FUNCTION public.set_assets_updated_at();

CREATE INDEX IF NOT EXISTS assets_status_idx           ON public.assets (status)          WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS assets_category_idx         ON public.assets (category)        WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS assets_insurance_expiry_idx ON public.assets (insurance_expiry) WHERE deleted_at IS NULL AND insurance_expiry IS NOT NULL;
CREATE INDEX IF NOT EXISTS assets_assigned_to_idx      ON public.assets (assigned_to)     WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS assets_deleted_at_idx       ON public.assets (deleted_at);

ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read assets"
  ON public.assets FOR SELECT
  USING (auth.uid() IS NOT NULL AND deleted_at IS NULL);

CREATE POLICY "Managers can insert assets"
  ON public.assets FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Managers can update assets"
  ON public.assets FOR UPDATE
  USING (auth.uid() IS NOT NULL);
