// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Trim whitespace — env vars with trailing spaces produce %20 in the
// WebSocket URL and cause realtime connections to silently fail.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string)?.trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string)?.trim();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY environment variable');
}

// ── Schema repair state ──────────────────────────────────────────────────────
let _schemaRepairPromise: Promise<boolean> | null = null;
let _lastRepairTime = 0;

async function attemptSchemaRepair(): Promise<boolean> {
  try {
    const storageKey = `sb-${new URL(SUPABASE_URL).hostname.split('.')[0]}-auth-token`;
    const raw = localStorage.getItem(storageKey);
    const accessToken = raw ? (JSON.parse(raw) as { access_token?: string }).access_token : null;
    if (!accessToken) return false;

    const res = await fetch(`${SUPABASE_URL}/functions/v1/ddl-executor`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${accessToken}`,
        apikey: SUPABASE_PUBLISHABLE_KEY,
      },
      body: JSON.stringify({ action: 'repairSchemaConfig' }),
    });
    if (!res.ok) return false;
    const body = await res.json();
    return body?.success === true;
  } catch {
    return false;
  }
}

const retryFetch: typeof fetch = async (input, init) => {
  const maxRetries = 3;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const res = await fetch(input, init);

    if (res.status === 406) {
      // Allow re-repair after 30s cooldown
      const now = Date.now();
      if (!_schemaRepairPromise || now - _lastRepairTime > 30_000) {
        _lastRepairTime = now;
        _schemaRepairPromise = attemptSchemaRepair();
      }
      const repaired = await _schemaRepairPromise;
      if (repaired && attempt < maxRetries) {
        await new Promise(r => setTimeout(r, 1000 * 2 ** attempt));
        continue;
      }
    }

    if (res.status === 503 && attempt < maxRetries) {
      await new Promise(r => setTimeout(r, 1000 * 2 ** attempt));
      continue;
    }
    return res;
  }
  return fetch(input, init);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: retryFetch,
  },
});

// ── Test-only hook (Playwright ops diagnostics) ────────────────────────────
// Exposes the client on window ONLY when VITE_EXPOSE_TEST_HOOKS=true, which
// is set exclusively in the Playwright CI workflow's build step — never in
// the real Vercel production build. Lets tests/ops-diagnose.spec.ts invoke
// any edge function through the SAME authenticated session Playwright's
// global-setup created, instead of requiring a human to paste JS into the
// browser console (error-prone — easy to paste into the wrong tool, as
// happened once already).
if ((import.meta.env.VITE_EXPOSE_TEST_HOOKS as string | undefined) === 'true') {
  (window as unknown as { __kdops_supabase__?: typeof supabase }).__kdops_supabase__ = supabase;
}
