// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Trim whitespace — env vars with trailing spaces produce %20 in the
// WebSocket URL and cause realtime connections to silently fail.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string)?.trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string)?.trim();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY environment variable');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ── Test-only hook (Playwright ops diagnostics) ────────────────────────────
// Exposes the client on window ONLY when VITE_EXPOSE_TEST_HOOKS=true, which
// is set exclusively in the Playwright CI workflow's build step — never in
// the real Vercel production build. Lets tests/ops-diagnose.spec.ts invoke
// any edge function through the SAME authenticated session Playwright's
// global-setup created, instead of requiring a human to paste JS into the
// browser console (error-prone — easy to paste into the wrong tool, as
// happened once already).
if ((import.meta.env.VITE_EXPOSE_TEST_HOOKS as string | undefined) === 'true') {
  (window as unknown as { __kdops_supabase__?: typeof supabase }).__kdops_supabase__ = supabase;
}
